### ISSUE TITLE
Change crafting requirements for Resonating Sapphire (increase crafting cost)

### ISSUE THREAD

**Issue by spannerman79** [Silly511/Resonant-Toolbox#1]
I haven't used your mod yet as I came across it via viewing the latest mod updates on Curse Forge.

A couple of things I'd like to ask;

Is it possible to change the actual values via config of the [Resonating Sapphire](https://github.com/Silly511/Resonant-Toolbox/wiki/Resonating-Sapphire)?  From viewing the crafting screenshot you need 80 Million RF & 16,000mb of Resonant Ender.  If the Resonating Sapphire is 1 of 4 needed requirements for Resonating Engine I would like an option to change the RF from 80 Million to _at least_ 250 Million RF and 32,000mb of Resonant Ender

My reasons are as follows;
- At that stage of end game 8 x Resonating Sapphire with a total of 2 Billion RF & 265,000mb of Resonant Ender is nothing (for Immortality Engine)  You'd have an Ender Pearl farm already in the End or using Magical Crops (among others).
-  Many modpack include mods like Draconic Evolution, Redstone Armory, Mekanism (specifically Fusion Reactor) so RF generation at far end game is very simple.

**Comment by Fadenfire** [comment]
the recipes I have now are placeholder recipes and soon I'm going to overhaul the recipes so that there really expensive. For now I'll change the recipe for the resonanting sapphire to what you said, but leave this issue open until I can get better recipes.

**Comment by Silly511** [comment]
#eb34f4c

**Comment by Fadenfire** [comment]
Sorry! I changed the recipes and will add them in version 1.0.4

**Comment by spannerman79** [comment]
> the recipes I have now are placeholder recipes and soon I'm going to overhaul the recipes so that there really expensive

I sort of figured that they were.  But sometimes modders forget that a user doesn't play with just their mod alone, or with their mod and any required depending mods.  Some modpacks are in the ~150 range.  Mine is up around ~300 mods with NotEnoughID's.

> For now I'll change the recipe for the resonanting sapphire to what you said, but leave this issue open until I can get better recipes.

No worries.  One possible suggestion is that you use 9 x Resonating Sapphire's to create a Resonating Sapphire block, and use those blocks in place of the Resonating Sapphire in the crafting recipe for the Immortality Engine.  That would mean for the Immortality Engine a user will need 40 x Resonating Sapphire's (plus other crafting components)  Its a basic increase, adds just one more block and makes the cost go up by 36 Resonating Sapphire's.  The sneaky/cleaver part is that the Immortality Engine cost is exponential to the cost of the individual Resonating Sapphire's. :smiling_imp:

**Comment by Fadenfire** [comment]
How's this for a really expensive recipe?

<img src="http://i.imgur.com/kNfc9oU.png">

**Comment by spannerman79** [comment]
Ooo getting there, Personally though, if its not a config option, have an output of just 1 x Resonating Sapphire instead of two.

Remember Mekanism allows for 5x ore duplication (for your Sapphire Ore), and if using ProjectE all you'll need (with Condenser & Energy Relay disabled in config) is extra utilities and their item transfer nodes with some world interaction upgrades pumping cobblestone into ProjectE EMC and if there was an EMC value set for the nether stars and Sapphires/Sapphire Ore meeting those requirements would be fairly easy.

I'd say the most common mods that users play with, well those that are tech minded would be Extra Utilities, Draconic Evolution, Mekanism & possibly even ProjectE.  Just look at some of the FTB packs and that would give you an idea of what roughly what people _mostly_ play with

**Comment by Fadenfire** [comment]
How about this:

<img src="http://i.imgur.com/kNfc9oU.png"  height=200>

 <img src="http://i.imgur.com/utopvgN.png"  height=200>

<img src="http://i.imgur.com/JfEklD8.png"  height=200>

That way one resonating engine costs 576 nether stars. Do you think that is expensive enough, or should I make it where 32 nether stars makes one Resonating Sapphire instead of two?

**Comment by spannerman79** [comment]
> That way one resonating engine costs 576 nether stars. Do you think that is expensive enough

Yeah :grinning: 

> should I make it where 32 nether stars makes one Resonating Sapphire

Me personally - I'd say one Resonating Sapphire.  Only because of what I've said before about modpacks and 5x ore duplication plus ProjectE etc.

From what I saw, the Immortality Engine is basically the user having `/god` but RF powered.  It should, to be blunt, _cost a fucking fuckload_ (what a player should say while their arse caves in at the cost :stuck_out_tongue: )

Remember once a user gets the Immortality Engine they won't even need to bother with Draconic Armor set.  They will be looking for ways to sell/exchange it with other users.

**Comment by Fadenfire** [comment]
How about this for the immortality engine:

<img src="http://i.imgur.com/wh8tBTy.png"  height=200>

<img src="http://i.imgur.com/fYHvR1M.png"  height=200>

<img src="http://i.imgur.com/Km0ygAD.png"  height=200>

First of all, I changed it so 32 nether stars makes one Resonating Sapphire, and added the recipes above. So basically, for one resonating engine you need 1,152 nether stars, and for one immortality engine you need 133,220 nether stars.

**Comment by spannerman79** [comment]
Much much better :smile: 

Some may later say that the changes you did were too much but from looking how you have done your mod everything in it is meant for end game, even further end game then Draconic Evolution current state (snapshot_9)

I'd close but but as you said before ( https://github.com/Silly511/Resonant-Toolbox/issues/1#issuecomment-181925077 ) to keep this open as these are placeholder recipes.

**Comment by Fadenfire** [comment]
I'll close this for now, but then reopen it when I have the capability to make the machines required for the recipes I have in mind.
